<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Layout extends Component
{
    public function render()
    {
        // notice we return the layout generated by Livewire here
        return view('layouts.app');
    }
}